# Generated by Django 5.2.4 on 2025-07-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(db_default=False, default=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('planning', 'Planning')], max_length=30, verbose_name='Status')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('priority', models.PositiveSmallIntegerField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], help_text='The priority level of the project.', verbose_name='Priority')),
                ('members', models.ManyToManyField(help_text='Users participating in the project', related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user who created the project.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(help_text='The user responsible for overseeing the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
    ]
