# Generated by Django 5.2.4 on 2025-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
