# Generated by Django 5.2.4 on 2025-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Low'), (4, 'Medium'), (3, 'High'), (2, 'Very High'), (1, 'Urgent')], default=(5, 'Low'), help_text='The priority level of the project.', verbose_name='Priority'),
        ),
    ]
