# Generated by Django 5.2.4 on 2025-07-10 11:14

import django.core.validators
import django.db.models.deletion
import src.choices.task
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(db_default=False, default=False)),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('close', 'Close')], default=src.choices.task.Status['new'], max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(5, 'Low'), (4, 'Medium'), (3, 'High'), (2, 'Very High'), (1, 'Urgent')], default=(5, 'Low'))),
                ('estimated_hours', models.DecimalField(decimal_places=2, help_text='Expected time to complete the task, in hours.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('deadline', models.DateTimeField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'unique_together': {('project', 'title')},
            },
        ),
    ]
