# Generated by Django 5.2.4 on 2025-07-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tag_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('planning', 'Planning')], default=('active', 'Active'), max_length=30, verbose_name='Status'),
        ),
    ]
