# Generated by Django 5.2.4 on 2025-07-21 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_end_date_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(db_default=False, default=False)),
                ('name', models.CharField(max_length=120, verbose_name='File Name')),
                ('file_path', models.CharField(max_length=255, verbose_name='File Path')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'db_table': 'project_files',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Files associated with this project.', related_name='projects', to='projects.projectfile'),
        ),
    ]
