# Generated by Django 5.2.4 on 2025-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectfile_project_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the task was completed.', null=True),
        ),
    ]
