# Generated by Django 5.2.4 on 2025-07-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_taskcomment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='created_by',
        ),
    ]
